version: "3.7"

services:
  gin-gonic:
    build: .
    volumes:
      - ./gin-gonic:/app
    ports:
      - 8080:8080

  exiter-0:
    build: .
    volumes:
      - ./exiter-0:/app

  exiter-1:
    build: .
    volumes:
      - ./exiter-1:/app
